Ingredient.create(nome: 'Arroz Integral', unidade_medida: 'Kilo')
Ingredient.create(nome: 'Tomate', unidade_medida: 'Unidade')
Ingredient.create(nome: 'Manjericão', unidade_medida: 'Grama')
Ingredient.create(nome: 'Peito de Frango', unidade_medida: 'Kilo')
Ingredient.create(nome: 'Alecrim', unidade_medida: 'Grama')