# USUÁRIOS 
User.create(name: 'gpioto', email: 'gabriel.piotogomes@gmail.com', password: 'gpioto')
User.create(name: 'lucascorrea', email: 'lucascorreasilvaa@gmail.com', password: 'lucascorrea')

# INGREDIENTES
Ingredient.create(name: 'Egg', unit_of_measure: 'Unit', picture: 'http://storage3d.com/storage/2011.06/67edb5856e833a248cc29bbd45467a0a.jpg')
Ingredient.create(name: 'Tomato', unit_of_measure: 'Unit', picture: 'http://icons.veryicon.com/256/Food%20%26%20Drinks/Paradise%20Fruits/Tomato.png')
Ingredient.create(name: 'Orange', unit_of_measure: 'Unit', picture: 'http://pngimg.com/upload/small/orange_PNG805.png')
Ingredient.create(name: 'Apple', unit_of_measure: 'Unit', picture: 'http://www.kimmelorchard.org/img/icon_apple_red_delicious.png')
Ingredient.create(name: 'Oregano', unit_of_measure: 'Gram', picture: 'http://static.wixstatic.com/media/fd14bd_39fb085cadd0482495e68db8a2873550.jpg_256')
Ingredient.create(name: 'Wholegraim rice', unit_of_measure: 'Gram', picture: 'http://static.wixstatic.com/media/020b10_ce681bebde07501862f6b54fdb911216.jpg_256')
Ingredient.create(name: 'Rice', unit_of_measure: 'Gram', picture: 'https://pbs.twimg.com/profile_images/701311216669556736/tyvsHM5d.jpg')
Ingredient.create(name: 'Basil', unit_of_measure: 'Gram', picture: 'http://www.concordessentials.com/images/basil%20sweet.jpg')
Ingredient.create(name: 'Chicken breast', unit_of_measure: 'Gram', picture: 'http://images.bigoven.com/image/upload/t_recipe-256/basic-baked-chicken-breast.jpg')
Ingredient.create(name: 'Rosemary', unit_of_measure: 'Gram', picture: 'https://dtgxwmigmg3gc.cloudfront.net/files/55b6ea7c52ba0b758a0035b4-icon-256x256.png')
Ingredient.create(name: 'Bacon', unit_of_measure: 'Gram', picture: 'http://images.bigoven.com/image/upload/t_recipe-256/turkey-bacon-2.jpg')
Ingredient.create(name: 'Condensed milk', unit_of_measure: 'Gram', picture: 'http://www.littlepersonshut.com/images/evaporatedmilk.jpg')
Ingredient.create(name: 'Chocolate sprinkles', unit_of_measure: 'Gram', picture: 'http://www.chocolatesyaks.cl/imagenes/productos/choc-6.jpg')
Ingredient.create(name: 'Heavy cream', unit_of_measure: 'Gram', picture: 'https://66.media.tumblr.com/avatar_597730af6efe_128.png')
Ingredient.create(name: 'Grated coconut', unit_of_measure: 'Gram', picture: 'http://www.mundoboaforma.com.br/wp-content/uploads/2015/03/059431P00007241981G.jpg')
Ingredient.create(name: 'Grated cheese', unit_of_measure: 'Gram', picture: 'http://www.grupodallas.com.br/dallasevoce/wp-content/uploads/2012/08/queijo-ralado.jpg')
Ingredient.create(name: 'Powdered chocolate', unit_of_measure: 'Gram', picture: 'https://4.bp.blogspot.com/-4tVXkQe0H5Y/VuWUt-OsELI/AAAAAAAAGyI/NfKVPT4-JTU0Rqp5jmqh6MdaHJrTZ8uKA/s1600/cocoa_powder.png')
Ingredient.create(name: 'Olive', unit_of_measure: 'Gram', picture: 'http://aqosta-commodities.com/wp-content/uploads/2015/08/olive-oil.jpg')
Ingredient.create(name: 'Wheat flour', unit_of_measure: 'Gram', picture: 'https://julieconstantinoudotcom.files.wordpress.com/2016/02/zea-flour.jpg?w=1000')
Ingredient.create(name: 'Baking powder', unit_of_measure: 'Gram', picture: 'https://itfnews.ir/wp-content/uploads/2016/08/images_1-1.jpg')
Ingredient.create(name: 'Milk', unit_of_measure: 'Milliliters', picture: 'https://65.media.tumblr.com/avatar_3bd283bcc7ba_128.png')

#LISTA DE INGREDIENTES
IngredientsUser.create(user_id: 1, ingredient_id: 1, quantity: 12)
IngredientsUser.create(user_id: 1, ingredient_id: 2, quantity: 5)
IngredientsUser.create(user_id: 1, ingredient_id: 3, quantity: 3)
IngredientsUser.create(user_id: 2, ingredient_id: 4, quantity: 3)
IngredientsUser.create(user_id: 2, ingredient_id: 5, quantity: 20)
IngredientsUser.create(user_id: 2, ingredient_id: 6, quantity: 50)
IngredientsUser.create(user_id: 3, ingredient_id: 7, quantity: 8)
IngredientsUser.create(user_id: 3, ingredient_id: 8, quantity: 15)
